### PR TITLE
Update payload.ps1

### PR DESCRIPTION
**Pull request by th3unknown90**

### CODE REVIEW

**Comment by GamehunterKaan** [comment]
Dude you just leaked your credentials

**Comment by th3unknown90** [comment]
Yeah can you delete it? I tried it didn’t work I guess fuck now I gotta
change everything thanks for letting me know

**Comment by GamehunterKaan** [comment]
Deleting a pull request is not allowed in GitHub. You will need to open a support request at https://support.github.com/contact

**Comment by th3unknown90** [comment]
So I just checked and my link isn’t there.. it’s only in our chat on GitHub
between you and I. But the .
Ps1 file is gone. Right?

**Comment by th3unknown90** [comment]
Or the patch-1 file

**Comment by th3unknown90** [comment]
Is it open to the public right now? While I wait for the reply from
support?

**Comment by GamehunterKaan** [comment]
It's public

**Comment by th3unknown90** [comment]
Fuck

**Comment by th3unknown90** [comment]
Nvm I got it. I deleted it.  Thanks is for the warning I’ve checked all and
it was my spam email. And secured all threats for the email.. thanks again
dude

**Pull request closed without merging**
